name: connect

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  connect:
    name: connect
    runs-on: [ubuntu-24.04-arm]
    steps:
      - name: info
        run: |
          whoami
          cat /proc/cpuinfo
          free -h
      - uses: self-actuated/connect-ssh@master
        with:
          block: true
